import pytest
from typing import Any, Iterator
import enum
import re

@pytest.fixture
def patterns() -> PatternsLib: ...
def pytest_addoption(parser: pytest.Parser) -> None: ...
def _should_use_color(config: pytest.Config) -> bool: ...
def pytest_assertrepr_compare(
    config: pytest.Config,
    op: str,
    left: Any,
    right: Any,
) -> list[str] | None: ...

class Status(enum.Enum):
    UNEXPECTED = 1
    OPTIONAL = 2
    EXPECTED = 3
    REFUSED = 4

    @property
    def symbol(self) -> str: ...

def describe_whitespace(line: str) -> str | None: ...
def _describe_whitespace_components(ws: str, prefix: str) -> str: ...
def tab_replace(line: str) -> str: ...
def to_control_picture(char: str) -> str: ...
def line_to_control_pictures(line: str) -> str: ...
def match(pattern: str, line: str) -> bool | re.Match[str] | None: ...

class Line:
    status: Status = Status.UNEXPECTED
    status_cause: str = ""

    def __init__(self, data: str): ...
    def matches(self, expectation: str) -> bool: ...
    def mark(self, status: Status, cause: str) -> None: ...

class Audit:
    content: list[Line]
    unmatched_expectations: list[tuple[str, str]]
    matched_refused: set[tuple[str, str]]
    # Track positions for JSON output:
    # (pattern_name, expected_line) -> line_number (1-based)
    _unmatched_positions: dict[tuple[str, str], int]
    # Track positions for matched refused:
    # (pattern_name, refused_line) -> line_number (1-based)
    _matched_refused_positions: dict[tuple[str, str], int]

    def __init__(self, content: str): ...
    def cursor(self) -> Iterator[Line]: ...
    def in_order(self, name: str, expected_lines: list[str]) -> None: ...
    def optional(self, name: str, tolerated_lines: list[str]) -> None: ...
    def refused(self, name: str, refused_lines: list[str]) -> None: ...
    def continuous(self, name: str, continuous_lines: list[str]) -> None: ...
    def _build_summary(self) -> str: ...
    def report(self, use_color: bool = True) -> Iterator[str]: ...
    def _collect_whitespace_issues(self) -> list[tuple[int, str]]: ...
    def _find_refused_line_numbers(
        self, name: str, pattern: str
    ) -> list[int]: ...
    def is_ok(self) -> bool: ...
    def _build_context(self, position: int) -> tuple[int, list[str]]: ...
    def to_json(self) -> dict[str, Any]: ...
    def _build_unmatched_entry(
        self, name: str, expected_line: str, *, is_primary: bool = True
    ) -> dict[str, Any]: ...
    def _build_matched_refused_entry(
        self, name: str, refused_line: str
    ) -> dict[str, Any]: ...

def format_line_report(
    status: Status,
    symbol: str,
    cause: str,
    line: str,
    original_line: str | None = None,
    use_color: bool = True,
) -> str: ...
def _format_whitespace(ws: str) -> str: ...
def pattern_lines(lines: str) -> list[str]: ...

class Pattern:
    name: str
    library: PatternsLib
    ops: list[tuple[str, str, Any]]
    inherited: set[str]

    def __init__(self, library: PatternsLib, name: str): ...

    # Modifiers (Verbs)

    def merge(self, *base_patterns: str) -> None: ...
    def normalize(self, mode: str) -> None: ...

    # Matches (Adjectives)

    def continuous(self, lines: str) -> None: ...
    def in_order(self, lines: str) -> None: ...
    def optional(self, lines: str) -> None: ...
    def refused(self, lines: str) -> None: ...

    # Internal API

    def flat_ops(self) -> Iterator[tuple[str, str, Any]]: ...
    def _audit(self, content: str) -> Audit: ...
    def generate_example(self) -> str: ...
    def _replace_wildcards(self, line: str) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class PatternsLib:
    def __getattr__(self, name: str) -> Pattern: ...
